### PR TITLE
fix: updated dependencies

### PR DESCRIPTION
**Pull request by AndriyKalashnykov**
Signed-off-by: Andriy Kalashnykov <AndriyKalashnykov@gmail.com>

### CODE REVIEW

**Comment by AndriyKalashnykov** [comment]
@oSethoum btw, did you have a chance to take a look at this before merging previous PR? https://github.com/oSethoum/simple-todo/pull/3#issue-1398896182

**Comment by oSethoum** [comment]
@AndriyKalashnykov these packages `@types/node` `@graphql-codegen/urql-introspection` exist already, they are in devDependencies.

**Comment by oSethoum** [comment]
@AndriyKalashnykov Yes, I took a look at [https://github.com/oSethoum/simple-todo/pull/3#issue-1398896182](https://github.com/oSethoum/simple-todo/pull/3#issue-1398896182) before merging, I left you a comment there. I will update it to use local schema file instead of the `backend` schema.

**Comment by AndriyKalashnykov** [comment]
@oSethoum sry, did not notice that. this is good new, i was hoping that it was the case.
you mentioned that `ent` generates `graphql` schemas and code for the go bakend out of go structs or em i missing something?

**Comment by oSethoum** [comment]
@AndriyKalashnykov `ent` has a specific way to declare database schema, and YES it does generate the graphql schema with the help of `entgql` extension. 
find out more in their [documentation](https://entgo.io )

**Pull request closed without merging**
